import openpyxl
import csv

correct_ko_map = {
    # ── Marketer ──────────────────────────────────────────────────────────────
    "The campaign delivered strong results last month.": "지난달 캠페인이 좋은 성과를 거뒀습니다.",
    "Our conversion rate increased by 15%.": "전환율이 15% 증가했습니다.",
    "We fell short of our target of 10,000 signups.": "가입자 수 1만 명 목표에는 미치지 못했습니다.",
    "Can you send me the report by Friday?": "금요일까지 보고서를 보내줄 수 있어요?",
    "I want to discuss the campaign plan.": "캠페인 계획에 대해 논의하고 싶습니다.",
    "We spent a significant budget on ads last quarter.": "지난 분기에 광고에 상당한 예산을 사용했습니다.",
    "Are you available this Friday afternoon?": "이번 주 금요일 오후에 시간 되세요?",
    "I think we should increase the budget.": "예산을 늘려야 할 것 같습니다.",
    "Could you explain the process to me?": "그 과정을 설명해 주실 수 있나요?",
    "I'd love to get your feedback on this copy.": "이 카피에 대한 의견을 듣고 싶습니다.",
    "I agree with your point.": "말씀하신 부분에 동의합니다.",
    "I don't think that's the right approach.": "그 방법은 적합하지 않은 것 같습니다.",
    "Can we reschedule the meeting to next week?": "회의를 다음 주로 미룰 수 있을까요?",
    "Please let me know when it's ready.": "준비되면 알려주세요.",
    "Thank you for your cooperation.": "협조해 주셔서 감사합니다.",
    "I'll share the file with you.": "파일 공유해 드릴게요.",
    "The CTR of the ad is 3.2%.": "해당 광고의 클릭률은 3.2%입니다.",
    "In summary, we met most of our targets.": "요약하면, 대부분의 목표를 달성했습니다.",
    "Why don't we try a new approach?": "새로운 방식을 시도해 보는 건 어떨까요?",
    "The deadline is April 30th.": "마감일은 4월 30일입니다.",
    "Version A outperformed Version B by a significant margin.": "버전 A가 버전 B보다 훨씬 좋은 성과를 보였습니다.",
    "The data indicates an upward trend in engagement.": "데이터를 보면 참여율이 상승 추세에 있습니다.",
    "The campaign underperformed against our projections.": "캠페인 성과가 예상치를 밑돌았습니다.",
    "This campaign generated a 3x return on investment.": "이번 캠페인은 투자 대비 3배의 수익을 창출했습니다.",
    "I'd recommend shifting our focus toward social media channels.": "소셜 미디어 채널 중심으로 방향을 전환하는 것을 권장합니다.",
    "We're requesting an additional budget allocation for Q3 to scale high-performing campaigns.": "성과가 좋은 캠페인을 확대하기 위해 3분기 추가 예산 배정을 요청드립니다.",
    "We'd love to explore a partnership opportunity with your team.": "귀 팀과 파트너십 기회를 모색하고 싶습니다.",
    "The objective of this campaign is to drive user acquisition.": "이번 캠페인의 목표는 신규 사용자 확보입니다.",
    "I'd prioritize this initiative given its potential impact.": "잠재적 영향력을 고려할 때 이 이니셔티브를 우선순위에 두겠습니다.",
    "Could we get some support from the dev team on the landing page build?": "랜딩 페이지 구축과 관련해 개발팀의 지원을 받을 수 있을까요?",
    "The spike in bounce rate may be attributed to the design change.": "이탈률 급등은 디자인 변경에서 비롯된 것으로 보입니다.",
    "Today I'd like to walk you through our Q2 marketing strategy.": "오늘은 2분기 마케팅 전략을 설명해 드리겠습니다.",
    "Thanks for the input — I'll revise the copy accordingly.": "의견 감사합니다. 그에 맞게 카피를 수정하겠습니다.",
    "The current timeline is challenging — could we discuss adjusting it?": "현재 일정이 빡빡한데, 조정하는 것에 대해 논의해볼 수 있을까요?",
    "Traffic grew 20% month-over-month, reaching X unique visitors.": "월간 트래픽이 20% 성장하여 X명의 순방문자를 기록했습니다.",
    "The ad creative isn't resonating with our target audience as expected.": "광고 크리에이티브가 예상만큼 타깃 오디언스에게 공감을 얻지 못하고 있습니다.",
    "We're set to launch the campaign tomorrow — here's what to expect.": "내일 캠페인 론칭 예정입니다. 앞으로 예상되는 내용을 공유드립니다.",
    "Competitor X is gaining ground in our core segment — here's how we can respond.": "경쟁사 X가 핵심 세그먼트에서 영향력을 키우고 있습니다. 대응 방안을 공유드립니다.",
    "We should focus on the 25-34 demographic who are active on Instagram.": "인스타그램에서 활발하게 활동하는 25~34세 연령대에 집중해야 합니다.",
    "In summary, our marketing initiatives exceeded targets in three key areas.": "요약하면, 우리 마케팅 활동이 세 가지 핵심 영역에서 목표를 초과 달성했습니다.",
    "I was hoping we could collaborate on the landing page — I'll handle the copy if your team can take care of the design.": "랜딩 페이지 협업을 제안드립니다. 제가 카피를 담당할 테니 귀 팀에서 디자인을 맡아주시면 좋겠습니다.",
    "The investment was justified — we achieved a 4x ROAS against a projected 2x.": "투자는 타당했습니다. 예상 ROAS 2배에서 실제 4배를 달성했습니다.",
    "We've identified an issue with the campaign that requires immediate attention.": "즉각적인 조치가 필요한 캠페인 문제를 발견했습니다.",
    "Based on our data, video ads tend to generate higher engagement in this segment.": "우리 데이터에 따르면, 이 세그먼트에서는 동영상 광고가 더 높은 참여도를 이끌어냅니다.",
    "That covers everything on my end — does anyone have questions or concerns?": "제 발표는 여기까지입니다. 질문이나 우려 사항이 있으신가요?",
    "Could you revise the ad headline to better align with our messaging?": "광고 헤드라인을 우리 메시지에 더 잘 맞게 수정해 주실 수 있나요?",
    "We're targeting end of month for delivery, with a checkpoint review on the 20th.": "월말 납품을 목표로 하고 있으며, 20일에 중간 점검을 진행할 예정입니다.",
    "I'll have the performance report in your inbox by EOD.": "오늘 업무 종료 전까지 성과 보고서를 메일로 보내드리겠습니다.",
    "We employ an omni-channel approach, including paid social, SEO, and email.": "유료 소셜, SEO, 이메일을 포함한 옴니채널 방식을 활용하고 있습니다.",
    "Our metrics outpace industry benchmarks by roughly 15%.": "우리 지표는 업계 벤치마크를 약 15% 앞서고 있습니다.",
    "Variant B achieved a 23% higher CTR, making it the clear winner.": "B 변형이 23% 더 높은 클릭률을 기록해 명확한 승자가 되었습니다.",
    "Please find attached the Q2 campaign performance report.": "2분기 캠페인 성과 보고서를 첨부하여 보내드립니다.",
    "The visual is a bit cluttered — simplifying it could improve click-through rates.": "비주얼이 다소 복잡한데, 단순화하면 클릭률이 향상될 수 있습니다.",
    "We segmented the audience into four distinct cohorts based on purchase intent.": "구매 의도에 따라 오디언스를 네 가지 코호트로 분류했습니다.",
    "Users move through our funnel from awareness to conversion, with a ~5% overall conversion rate.": "사용자들은 인지부터 전환까지 퍼널을 이동하며, 전체 전환율은 약 5%입니다.",
    "There's significant room to improve our SEO performance, particularly around long-tail keywords.": "특히 롱테일 키워드를 중심으로 SEO 성과를 개선할 여지가 상당히 있습니다.",
    "I'd like to bring everyone up to speed on where the project stands.": "현재 프로젝트 진행 상황을 모두와 공유하고자 합니다.",
    "The cost is on the higher side, but the targeting precision justifies the spend.": "비용이 다소 높지만, 타기팅 정밀도를 고려하면 그만한 가치가 있습니다.",
    "The uplift in sales is likely driven by our recent campaign and the seasonal demand.": "매출 상승은 최근 캠페인과 계절적 수요에 의한 것으로 보입니다.",
    "Our Q3 goal is to grow our user base by 20%, with a focus on organic acquisition.": "3분기 목표는 오가닉 유입 중심으로 사용자 기반을 20% 성장시키는 것입니다.",
    "We'd like to discuss pivoting the campaign strategy to better align with current market trends.": "현재 시장 트렌드에 더 잘 맞도록 캠페인 전략을 전환하는 것에 대해 논의하고 싶습니다.",
    "This doesn't quite match the brief — let me walk you through the key areas we'd like to revisit.": "브리프와 다소 차이가 있습니다. 다시 검토했으면 하는 주요 부분을 설명해 드리겠습니다.",
    "We'd be open to a data-sharing arrangement that could benefit both parties.": "양측 모두에게 유익한 데이터 공유 방식을 열린 마음으로 검토해 볼 의향이 있습니다.",
    "We're on track for launch — all assets are approved and the team is briefed.": "론칭 준비가 순조롭게 진행 중입니다. 모든 에셋이 승인됐고 팀도 브리핑을 받았습니다.",
    "We're pushing the launch date back to [DATE] to allow time for final QA.": "최종 QA 시간을 확보하기 위해 론칭일을 [날짜]로 연기합니다.",
    "We came close to our target, finishing at 92% of the Q2 goal.": "2분기 목표의 92%를 달성하며 목표에 근접했습니다.",
    "The data reveals an interesting pattern — users who engage with video content are 3x more likely to convert.": "데이터에서 흥미로운 패턴이 발견됐습니다. 영상 콘텐츠를 이용하는 사용자는 전환 가능성이 3배 높습니다.",
    "Email remains our top-performing channel, consistently driving the highest ROI.": "이메일은 지속적으로 가장 높은 ROI를 창출하는 최고 성과 채널입니다.",
    "Our next steps are to analyze the data, refine targeting, and scale the top-performing ads.": "다음 단계는 데이터 분석, 타기팅 정교화, 성과 상위 광고 확대입니다.",
    "Overall, the campaign exceeded expectations — hitting 110% of our KPIs and delivering strong brand lift.": "전반적으로 캠페인은 KPI 110%를 달성하고 강력한 브랜드 인지도 향상을 이끌며 기대를 뛰어넘었습니다.",
    "Our marketing strategy is yielding measurable results, with a 25% YoY improvement in customer acquisition cost.": "우리 마케팅 전략은 고객 유치 비용 전년 대비 25% 개선이라는 뚜렷한 성과를 내고 있습니다.",
    "I'd like to make the case for a budget increase, given the strong ROAS we've demonstrated this quarter.": "이번 분기에 입증된 높은 ROAS를 근거로 예산 증액을 제안드리고 싶습니다.",
    "We're proposing a strategic pivot — shifting from broad acquisition to a retention-first growth model.": "광범위한 신규 유입에서 리텐션 우선 성장 모델로 전략적 전환을 제안합니다.",
    "There's execution risk here, particularly around creative fatigue and audience saturation.": "특히 크리에이티브 피로와 오디언스 포화를 중심으로 실행 리스크가 있습니다.",
    "We need to develop a proactive response to the competitive pressure, rather than simply reacting.": "단순히 반응하기보다는 경쟁 압박에 선제적으로 대응하는 전략을 마련해야 합니다.",
    "My hypothesis is that the new audience segment will outperform the existing cohort by at least 15%.": "새로운 오디언스 세그먼트가 기존 코호트보다 최소 15% 이상 높은 성과를 낼 것으로 가설을 세웁니다.",
    "The results are nuanced — while we exceeded reach targets, conversion efficiency was below benchmark.": "결과가 복잡합니다. 도달 목표는 초과했지만 전환 효율은 벤치마크에 미치지 못했습니다.",
    "Investing in brand equity now will compound our performance marketing returns over time.": "지금 브랜드 자산에 투자하면 퍼포먼스 마케팅 수익이 시간이 지남에 따라 복리로 늘어날 것입니다.",
    "I'll take you through the key findings and what they mean for our Q3 strategy.": "주요 발견 사항과 3분기 전략에 미치는 의미를 설명해 드리겠습니다.",
    "Given the underperformance, I recommend pausing the campaign and conducting a root cause analysis before reallocating the budget.": "성과 부진을 감안하여, 예산 재배분 전에 캠페인을 일시 중단하고 근본 원인 분석을 실시할 것을 권장합니다.",
    "I'd recommend piloting TikTok as a growth channel, starting with a limited test budget to validate performance before scaling.": "성과 검증 후 확대하는 방식으로 소규모 테스트 예산부터 시작해 틱톡을 성장 채널로 시범 운영할 것을 권장합니다.",
    "While our campaign likely contributed to the sales uplift, we need to account for external factors like seasonality and the product launch.": "캠페인이 매출 상승에 기여한 것은 사실이지만, 계절성이나 제품 출시 같은 외부 요인도 고려해야 합니다.",
    "We should optimize our channel mix based on incrementality testing rather than last-click attribution.": "라스트 클릭 기여 방식 대신 증분 테스트를 기반으로 채널 믹스를 최적화해야 합니다.",
    "I'd like each team member to own a specific workstream — this will improve accountability and execution speed.": "각 팀원이 특정 업무 흐름을 담당하도록 하겠습니다. 이를 통해 책임감과 실행 속도가 향상될 것입니다.",
    "The data suggests positive results, though the sample size limits our statistical confidence.": "데이터는 긍정적인 결과를 시사하지만, 샘플 크기가 작아 통계적 신뢰도가 제한됩니다.",
    "Based on current trends, we're projecting a 20% QoQ growth in leads, assuming stable CPC.": "현재 추세를 기반으로, CPC가 안정적으로 유지된다는 가정 하에 리드의 전 분기 대비 20% 성장을 전망합니다.",
    "Q2 results exceeded plan, driven by email and paid social — I'll focus on what this means for our H2 strategy.": "이메일과 유료 소셜이 이끈 2분기 결과가 계획을 초과했습니다. 이것이 하반기 전략에 미치는 의미를 설명드리겠습니다.",
    "I'd like to align with the product team to ensure our messaging is consistent with the upcoming feature release.": "곧 있을 기능 출시에 맞춰 메시지가 일관되도록 제품팀과 조율하고 싶습니다.",
    "This initiative directly supports our company OKR of increasing net revenue retention by 10%.": "이 이니셔티브는 순 매출 리텐션 10% 향상이라는 회사 OKR을 직접적으로 지원합니다.",
    "I'd appreciate your review of the strategy document — particularly the targeting rationale and budget allocation.": "전략 문서, 특히 타기팅 근거와 예산 배분 부분을 검토해 주시면 감사하겠습니다.",
    "Content marketing has a proven track record of reducing CAC over time — a 30% increase in content investment could yield long-term efficiency gains.": "콘텐츠 마케팅은 CAC를 낮추는 효과가 입증되어 있습니다. 콘텐츠 투자를 30% 늘리면 장기적으로 효율 개선이 기대됩니다.",
    "Given our projected annual spend with your platform, I'd like to discuss a volume-based pricing structure.": "귀 플랫폼에 대한 예상 연간 지출 규모를 감안하여 볼륨 기반 가격 구조에 대해 논의하고 싶습니다.",
    "The results are multifaceted — I'll break down performance by channel, audience, and creative to give a full picture.": "결과가 다면적입니다. 전체적인 그림을 보여드리기 위해 채널, 오디언스, 크리에이티브별로 성과를 분석하겠습니다.",
    "We're evolving our measurement framework from click-based metrics to business outcome-driven KPIs.": "측정 체계를 클릭 기반 지표에서 비즈니스 성과 중심 KPI로 전환하고 있습니다.",
    "I'd like to propose a co-marketing initiative that leverages both our audiences for mutual growth.": "양측 오디언스를 활용한 공동 마케팅 이니셔티브를 제안드리고 싶습니다.",
    "With the reduced budget, I'd recommend focusing resources on our highest-ROI channels and pausing experimental spend.": "예산 감축을 고려하여, ROI가 가장 높은 채널에 자원을 집중하고 실험적 지출을 일시 중단할 것을 권장합니다.",
    "Attribution remains a challenge — I recommend a multi-touch model to more accurately reflect the customer journey.": "기여 분석은 여전히 어려운 과제입니다. 고객 여정을 더 정확히 반영하기 위해 멀티 터치 모델을 권장합니다.",
    "This is our annual marketing roadmap, aligned to our company's growth objectives and prioritized by expected ROI.": "이것은 회사 성장 목표에 맞게 조정되고 예상 ROI에 따라 우선순위가 매겨진 연간 마케팅 로드맵입니다.",
    "We're evaluating international expansion, starting with markets that show organic demand signals for our product.": "우리 제품에 대한 자연적 수요 신호가 나타나는 시장부터 시작하는 국제 시장 진출을 검토하고 있습니다.",
    "Our vision is to build a best-in-class marketing function that drives compounding growth and brand equity over the long term.": "우리의 비전은 장기적으로 복리 성장과 브랜드 자산을 이끄는 최고 수준의 마케팅 기능을 구축하는 것입니다.",

    # ── Designer ──────────────────────────────────────────────────────────────
    "Can I get feedback on this?": "이것에 대한 피드백을 받을 수 있을까요?",
    "I'll walk you through the designs I made.": "제가 만든 디자인을 설명해 드리겠습니다.",
    "This version is better than the previous one.": "이번 버전이 이전 것보다 낫습니다.",
    "Can you walk me through what you mean?": "무슨 말씀인지 좀 더 설명해 주실 수 있나요?",
    "I'd love to get your input on this flow.": "이 플로우에 대한 의견을 듣고 싶습니다.",
    "Does this design meet what you had in mind?": "이 디자인이 생각하셨던 것과 맞나요?",
    "I'd like to hear your thoughts on this.": "이것에 대한 생각을 듣고 싶습니다.",
    "Let me take you through the key decisions I made.": "제가 내린 주요 결정들을 설명해 드리겠습니다.",
    "This iteration was informed by user feedback.": "이번 수정안은 사용자 피드백을 반영했습니다.",
    "I'd appreciate any critical feedback you might have.": "날카로운 피드백이 있으시면 말씀해 주시면 감사하겠습니다.",
    "This icon doesn't quite work here.": "이 아이콘은 여기에 잘 맞지 않습니다.",
    "I think this button is a bit too large.": "이 버튼이 좀 크게 느껴집니다.",
    "The typography feels a bit hard to read.": "타이포그래피가 읽기 다소 어렵게 느껴집니다.",
    "The spacing between elements feels inconsistent.": "요소 간 간격이 일관성이 없게 느껴집니다.",
    "Can you make the CTA button stand out more?": "CTA 버튼이 더 눈에 띄도록 해주실 수 있나요?",
    "I feel this needs a little more polish.": "이 부분에 마무리 손질이 조금 더 필요한 것 같습니다.",
    "The visual hierarchy is something we should address.": "시각적 위계 구조를 개선할 필요가 있습니다.",
    "This design lacks clarity in the navigation.": "이 디자인은 네비게이션 명확성이 부족합니다.",
    "I'm not entirely convinced this direction is right.": "이 방향이 맞는지 아직 확신이 서지 않습니다.",
    "Could we revisit the decision we made around onboarding?": "온보딩에 대해 내렸던 결정을 다시 검토할 수 있을까요?",
    "I focused on keeping it simple.": "단순하게 유지하는 데 집중했습니다.",
    "I designed this screen for users who want to check their history.": "이 화면은 이용 내역을 확인하고 싶은 사용자를 위해 디자인했습니다.",
    "I changed the main color to blue.": "메인 컬러를 파란색으로 변경했습니다.",
    "This screen is what users see when they first open the app.": "이 화면은 사용자가 앱을 처음 열었을 때 보는 화면입니다.",
    "Let me walk you through the new onboarding flow.": "새로운 온보딩 플로우를 설명해 드리겠습니다.",
    "Here's what I'll be presenting today.": "오늘 발표할 내용입니다.",
    "I've tried to strike a balance between aesthetics and usability.": "미적 요소와 사용성 사이의 균형을 잡으려 했습니다.",
    "This design pattern was inspired by Material Design.": "이 디자인 패턴은 머티리얼 디자인에서 영감을 받았습니다.",
    "The rationale behind this decision is explained in the notes.": "이 결정의 근거는 노트에 설명되어 있습니다.",
    "I took a user-centered approach to this redesign.": "이번 리디자인에는 사용자 중심 접근 방식을 적용했습니다.",
    "Please check the spec file I sent.": "제가 보낸 스펙 파일을 확인해 주세요.",
    "There are some issues with the animation.": "애니메이션에 몇 가지 문제가 있습니다.",
    "I'll upload the assets to Figma.": "에셋을 피그마에 업로드하겠습니다.",
    "Can you let me know when you've finished implementing this?": "구현이 완료되면 알려주실 수 있나요?",
    "The component isn't rendering as expected.": "컴포넌트가 예상대로 렌더링되지 않고 있습니다.",
    "Could you align the padding to match the specs I shared?": "제가 공유한 스펙에 맞게 패딩을 정렬해 주실 수 있나요?",
    "The hover state should transition smoothly.": "호버 상태가 부드럽게 전환되어야 합니다.",
    "I'll annotate the specs so engineers don't have to guess.": "개발자들이 추측할 필요가 없도록 스펙에 주석을 달겠습니다.",
    "Let's sync up to make sure we're on the same page.": "모두 같은 이해를 갖고 있는지 확인하기 위해 소통해 봅시다.",
    "I think this interaction could use a bit more refinement.": "이 인터랙션은 좀 더 다듬을 필요가 있는 것 같습니다.",
    "Users are saying the app is hard to use.": "사용자들이 앱 사용이 어렵다고 말하고 있습니다.",
    "We ran user testing with 5 users last week.": "지난주에 사용자 5명을 대상으로 사용성 테스트를 진행했습니다.",
    "Users tend to lose track of where they are in the app.": "사용자들이 앱에서 자신의 위치를 파악하지 못하는 경향이 있습니다.",
    "The interview was conducted with 12 participants.": "인터뷰는 12명의 참여자를 대상으로 진행됐습니다.",
    "The pain point users mentioned most is confusing navigation.": "사용자들이 가장 많이 언급한 불편함은 혼란스러운 네비게이션입니다.",
    "Based on user feedback, we've gained valuable insights into user behavior.": "사용자 피드백을 통해 사용자 행동에 대한 귀중한 인사이트를 얻었습니다.",
    "The usability test revealed that users struggled to complete this task.": "사용성 테스트에서 사용자들이 이 작업을 완료하는 데 어려움을 겪는 것으로 나타났습니다.",
    "We're seeing a pattern where users drop off at the payment screen.": "사용자들이 결제 화면에서 이탈하는 패턴이 나타나고 있습니다.",
    "This feature addresses a core user need we identified in research.": "이 기능은 리서치에서 파악한 핵심 사용자 니즈를 해결합니다.",
    "The findings align well with what we hypothesized earlier.": "결과는 우리가 이전에 세운 가설과 잘 일치합니다.",
    "We should keep the spacing consistent.": "간격을 일관되게 유지해야 합니다.",
    "We need to align this with our design guidelines.": "이것을 우리 디자인 가이드라인에 맞춰야 합니다.",
    "This component doesn't follow our design tokens.": "이 컴포넌트가 우리 디자인 토큰을 따르지 않고 있습니다.",
    "Let's make sure all icons are consistent in size and style.": "모든 아이콘의 크기와 스타일이 일관성 있는지 확인합시다.",
    "We should document this component for future developer reference.": "향후 개발자 참고를 위해 이 컴포넌트를 문서화해야 합니다.",
    "This pattern breaks the consistency we've established throughout the system.": "이 패턴은 시스템 전체에 걸쳐 구축해온 일관성을 깨뜨립니다.",
    "The component library needs to be audited for outdated patterns.": "컴포넌트 라이브러리에서 오래된 패턴을 검토해야 합니다.",
    "We should deprecate the old button styles by end of quarter.": "분기 말까지 기존 버튼 스타일을 사용 중단 처리해야 합니다.",
    "I'll flag this as design debt to address in a future sprint.": "이것을 향후 스프린트에서 해결할 디자인 부채로 표시해 두겠습니다.",
    "This pattern solves the same problem our existing modal does.": "이 패턴은 기존 모달이 해결하는 것과 동일한 문제를 해결합니다.",
    "I'll send you the Figma file link.": "피그마 파일 링크를 보내드리겠습니다.",
    "I uploaded the files to Figma.": "피그마에 파일을 업로드했습니다.",
    "I've annotated the interactions so devs know how they work.": "개발자들이 작동 방식을 이해할 수 있도록 인터랙션에 주석을 달았습니다.",
    "The redlines are included in the spec file.": "스펙 파일에 치수 표시가 포함되어 있습니다.",
    "Can you check if this matches the design?": "이것이 디자인과 일치하는지 확인해 주실 수 있나요?",
    "I've prepared a handoff document outlining the key design decisions.": "주요 디자인 결정 사항을 정리한 인계 문서를 준비했습니다.",
    "Let me know if you need any clarification on the spec.": "스펙에 대해 명확하게 해드릴 부분이 있으면 알려주세요.",
    "I've set up the Figma file so it's easy for engineers to navigate.": "개발자들이 쉽게 탐색할 수 있도록 피그마 파일을 구성했습니다.",
    "I've made sure all assets follow a consistent naming convention.": "모든 에셋이 일관된 이름 규칙을 따르는지 확인했습니다.",
    "Please refer to the component specs before starting implementation.": "구현을 시작하기 전에 컴포넌트 스펙을 참조해 주세요.",
    "We need to discuss the design direction.": "디자인 방향에 대해 논의해야 합니다.",
    "I don't agree with this direction.": "이 방향에 동의하지 않습니다.",
    "Let me note your concern and follow up.": "말씀하신 우려 사항을 메모해 두고 후속 조치를 취하겠습니다.",
    "We've made significant progress since the last meeting.": "지난 회의 이후 상당한 진전을 이뤘습니다.",
    "This aligns with the product vision leadership has set.": "이것은 리더십이 설정한 제품 비전과 일치합니다.",
    "I'd like to bring everyone up to speed on the latest designs.": "최신 디자인에 대해 모두에게 공유하고자 합니다.",
    "Before we dive in, I want to align on the goals for this session.": "시작하기 전에 이 세션의 목표를 함께 맞춰보고 싶습니다.",
    "I want to flag a risk that could impact our timeline.": "일정에 영향을 미칠 수 있는 리스크를 공유하고 싶습니다.",
    "Can we get consensus on the direction before moving forward?": "진행하기 전에 방향에 대한 합의를 얻을 수 있을까요?",
    "I appreciate the feedback — I'll take that on board and get back to you.": "피드백 감사합니다. 잘 참고해서 다시 연락드리겠습니다.",
    "I'll revise it based on your feedback.": "피드백을 바탕으로 수정하겠습니다.",
    "I think we need a simpler design.": "더 단순한 디자인이 필요할 것 같습니다.",
    "Can you take another look at this revised screen?": "수정된 화면을 다시 한 번 봐주실 수 있나요?",
    "I've updated the design based on our discussion.": "논의 내용을 바탕으로 디자인을 업데이트했습니다.",
    "I'll need one more round to nail this down.": "이것을 완성하려면 한 번 더 수정이 필요합니다.",
    "I've incorporated most of the feedback from last week.": "지난주 피드백의 대부분을 반영했습니다.",
    "This iteration addresses the edge cases that were previously overlooked.": "이번 수정안은 이전에 간과됐던 엣지 케이스들을 다루고 있습니다.",
    "I want to pressure-test this design before we call it final.": "최종 확정 전에 이 디자인을 철저히 검증해 보고 싶습니다.",
    "I'll take a stab at a quick wireframe to visualize the idea.": "아이디어를 시각화하기 위해 빠르게 와이어프레임을 만들어 보겠습니다.",
    "Let me put together a few options for you to vet before we commit.": "확정하기 전에 검토하실 수 있도록 몇 가지 옵션을 만들어 드리겠습니다.",
    "Let me know what you think.": "어떻게 생각하시는지 말씀해 주세요.",
    "I have a question about the project timeline.": "프로젝트 일정에 대해 질문이 있습니다.",
    "Can we table this topic for the next meeting?": "이 주제는 다음 회의로 넘길 수 있을까요?",
    "I'll take ownership of the user flow.": "제가 사용자 플로우를 담당하겠습니다.",
    "I'll look into this and get back to you with my thoughts.": "이 부분을 살펴보고 제 생각을 다시 전달해 드리겠습니다.",
    "I think we're at risk of scope creep here.": "여기서 범위가 무분별하게 확장될 위험이 있는 것 같습니다.",
    "Let's make sure we're all pulling in the same direction.": "모두가 같은 방향을 향하고 있는지 확인합시다.",
    "I don't want us to boil the ocean here — let's stay focused.": "너무 많은 것을 한꺼번에 하려 하지 말고 집중합시다.",
    "This is a good opportunity to step back and look at the bigger picture.": "이것은 한발 물러서서 큰 그림을 볼 좋은 기회입니다.",
    "I'd like to challenge the assumption that simplicity always wins.": "단순함이 항상 이긴다는 가정에 의문을 제기하고 싶습니다.",

    # ── Developer ─────────────────────────────────────────────────────────────
    "This could cause performance issues.": "이 부분이 성능 문제를 일으킬 수 있습니다.",
    "Can you explain why you chose this approach?": "이 방법을 선택한 이유를 설명해 주실 수 있나요?",
    "I think we should refactor this part.": "이 부분을 리팩토링해야 할 것 같습니다.",
    "This variable name is a bit unclear.": "이 변수 이름이 다소 불명확합니다.",
    "We should also handle edge cases here.": "여기서 엣지 케이스도 처리해야 합니다.",
    "This logic could be simplified a bit.": "이 로직을 조금 더 단순화할 수 있을 것 같습니다.",
    "The test coverage here looks insufficient.": "이 부분의 테스트 커버리지가 부족해 보입니다.",
    "This function is doing too many things.": "이 함수가 너무 많은 일을 하고 있습니다.",
    "This pattern could make future maintenance more difficult.": "이 패턴은 향후 유지보수를 더 어렵게 만들 수 있습니다.",
    "Could you verify this aligns with all the requirements?": "이것이 모든 요구사항에 부합하는지 확인해 주실 수 있나요?",
    "I'm not sure this library is the right fit for our use case.": "이 라이브러리가 우리 사용 사례에 적합한지 잘 모르겠습니다.",
    "Let's weigh the trade-offs of this approach.": "이 접근 방식의 트레이드오프를 따져봅시다.",
    "Our current architecture may struggle to scale under increased load.": "현재 아키텍처는 부하가 증가하면 확장에 어려움을 겪을 수 있습니다.",
    "The technical debt here is becoming a bottleneck — I think we should prioritize addressing it.": "여기서 기술 부채가 병목 현상이 되고 있습니다. 이를 우선적으로 해결해야 할 것 같습니다.",
    "This solution offers better long-term maintainability, even if the initial setup takes more time.": "초기 설정에 시간이 더 걸리더라도 이 솔루션이 장기적으로 더 나은 유지보수성을 제공합니다.",
    "We have two main approaches here — let me walk you through the trade-offs of each.": "여기에 두 가지 주요 접근 방식이 있습니다. 각각의 트레이드오프를 설명해 드리겠습니다.",
    "Migrating to a microservices architecture introduces significant operational complexity.": "마이크로서비스 아키텍처로 전환하면 운영 복잡성이 크게 증가합니다.",
    "This API design deviates from RESTful conventions in a few key areas.": "이 API 설계는 몇 가지 핵심 영역에서 RESTful 관례를 벗어납니다.",
    "Implementing a caching layer here could significantly reduce response times.": "여기에 캐싱 레이어를 구현하면 응답 시간을 크게 줄일 수 있습니다.",
    "This architectural decision has broad implications across the entire system — we should align the team before proceeding.": "이 아키텍처 결정은 전체 시스템에 광범위한 영향을 미칩니다. 진행하기 전에 팀의 합의를 얻어야 합니다.",
    "I'm working on the new API integration today.": "오늘은 새로운 API 연동 작업을 하고 있습니다.",
    "I wrapped up the authentication module yesterday.": "어제 인증 모듈 작업을 마무리했습니다.",
    "I'm blocked on the deployment issue — I could use some help.": "배포 문제로 막혀 있는데 도움이 필요합니다.",
    "This task seems too large to fit in one sprint — should we break it down?": "이 작업은 한 스프린트에 담기엔 너무 큰 것 같습니다. 세분화할까요?",
    "This sprint, we completed the user authentication flow and the dashboard redesign.": "이번 스프린트에서 사용자 인증 플로우와 대시보드 리디자인을 완료했습니다.",
    "One thing we could improve next sprint is our PR review turnaround time.": "다음 스프린트에서 개선할 수 있는 한 가지는 PR 리뷰 처리 속도입니다.",
    "I'd suggest bumping this feature up in priority given the upcoming release.": "곧 있을 릴리즈를 고려하면 이 기능의 우선순위를 높이는 것을 제안합니다.",
    "I'd recommend allocating some capacity this sprint for addressing our highest-priority tech debt.": "이번 스프린트에 가장 높은 우선순위의 기술 부채를 해결할 시간을 확보하는 것을 권장합니다.",
    "We fell short of our sprint goal due to an unexpected infrastructure outage mid-sprint.": "스프린트 중간에 예상치 못한 인프라 장애로 스프린트 목표를 달성하지 못했습니다.",
    "This task is blocked by a dependency on the data pipeline work — I'd suggest deferring it to the next sprint.": "이 작업은 데이터 파이프라인 작업에 의존하고 있어 차단되어 있습니다. 다음 스프린트로 미루는 것을 제안합니다.",
    "I've spotted a bug in the checkout flow — I'll file a ticket.": "결제 플로우에서 버그를 발견했습니다. 티켓을 등록하겠습니다.",
    "This bug is reproducible only in the production environment with iOS 16.": "이 버그는 iOS 16 환경의 프로덕션에서만 재현됩니다.",
    "This bug is blocking users from completing checkout, which directly impacts revenue.": "이 버그로 인해 사용자들이 결제를 완료하지 못하고 있으며, 이는 매출에 직접적인 영향을 미칩니다.",
    "The root cause is deeper than expected — fixing this will take an additional day.": "근본 원인이 예상보다 더 깊이 있습니다. 수정에 하루가 더 필요합니다.",
    "This bug may have a wider impact — it could affect the payment and notification modules as well.": "이 버그는 더 넓은 영향을 미칠 수 있습니다. 결제 및 알림 모듈에도 영향을 줄 수 있습니다.",
    "I've applied a temporary workaround — we should revisit this with a proper fix in the next sprint.": "임시 해결책을 적용했습니다. 다음 스프린트에서 제대로 된 수정으로 다시 살펴봐야 합니다.",
    "The root cause analysis points to a race condition in the session management module.": "근본 원인 분석 결과 세션 관리 모듈의 경쟁 조건이 원인으로 파악됐습니다.",
    "This is an intermittent bug — it only surfaces under high concurrency conditions.": "이것은 간헐적 버그로 높은 동시성 환경에서만 나타납니다.",
    "We should run regression tests to ensure this fix doesn't introduce any unintended side effects.": "이 수정이 의도치 않은 부작용을 일으키지 않도록 회귀 테스트를 실행해야 합니다.",
    "Could you put together a minimal reproducible example so we can isolate the issue?": "문제를 특정하기 위해 최소 재현 예시를 만들어 주실 수 있나요?",
    "Could you share the API endpoint specs when you get a chance?": "시간이 되실 때 API 엔드포인트 스펙을 공유해 주실 수 있나요?",
    "The API response format doesn't match what's in the documentation.": "API 응답 형식이 문서에 있는 것과 일치하지 않습니다.",
    "I'd suggest migrating the API authentication to OAuth 2.0 for better security.": "보안 강화를 위해 API 인증을 OAuth 2.0으로 마이그레이션하는 것을 제안합니다.",
    "The number of API calls is causing a performance bottleneck — we should look into batching requests.": "API 호출 횟수로 인해 성능 병목이 발생하고 있습니다. 요청 배치 처리를 검토해야 합니다.",
    "I think we should introduce API versioning to maintain backward compatibility.": "하위 호환성을 유지하기 위해 API 버전 관리를 도입해야 할 것 같습니다.",
    "We need to ensure idempotency for our POST endpoints to prevent duplicate transactions.": "중복 트랜잭션을 방지하기 위해 POST 엔드포인트의 멱등성을 보장해야 합니다.",
    "Our API response times are consistently exceeding our 200ms SLA — we need to investigate.": "API 응답 시간이 지속적으로 200ms SLA를 초과하고 있습니다. 조사가 필요합니다.",
    "We can introduce breaking changes in a new API version while maintaining the existing endpoints for backward compatibility.": "기존 엔드포인트를 하위 호환성을 위해 유지하면서 새로운 API 버전에 호환성을 깨는 변경 사항을 도입할 수 있습니다.",
    "Our reliance on this third-party API introduces a single point of failure — we should implement a fallback.": "이 서드파티 API에 대한 의존성이 단일 장애 지점을 만듭니다. 폴백을 구현해야 합니다.",
    "We should redesign our request strategy to stay within the API rate limits and avoid throttling.": "API 속도 제한을 준수하고 스로틀링을 방지하기 위해 요청 전략을 재설계해야 합니다.",
    "This function calculates the user's score based on their activity.": "이 함수는 사용자의 활동을 기반으로 점수를 계산합니다.",
    "I took this approach because the original method had performance issues at scale.": "원래 방식이 규모가 커질 때 성능 문제가 있었기 때문에 이 방법을 선택했습니다.",
    "I chose the Observer pattern here because we need to decouple the event source from its handlers.": "이벤트 소스와 핸들러를 분리해야 했기 때문에 옵저버 패턴을 선택했습니다.",
    "This is a work in progress — I still need to add error handling and write tests.": "아직 작업 중입니다. 에러 처리 추가와 테스트 작성이 필요합니다.",
    "I've left a TODO here — this section needs refactoring once we finalize the data model.": "여기에 TODO를 남겨뒀습니다. 데이터 모델이 확정되면 이 부분을 리팩토링해야 합니다.",
    "This async approach prevents race conditions by ensuring each operation completes before the next begins.": "이 비동기 방식은 각 작업이 완료된 후 다음 작업이 시작되도록 하여 경쟁 조건을 방지합니다.",
    "This abstraction layer decouples the business logic from the data access layer, making it easier to test and swap implementations.": "이 추상화 레이어는 비즈니스 로직을 데이터 접근 레이어에서 분리하여 테스트와 구현 교체를 쉽게 합니다.",
    "This algorithm runs in O(n log n) time, which is a significant improvement over the previous O(n²) approach.": "이 알고리즘은 O(n log n) 시간 복잡도로 실행되며, 이전의 O(n²) 방식보다 크게 개선됐습니다.",
    "Dependency injection here allows us to mock dependencies in tests and swap implementations without changing the core logic.": "여기서 의존성 주입을 사용하면 테스트에서 의존성을 모킹하고 핵심 로직을 변경하지 않고도 구현을 교체할 수 있습니다.",
    "We cache the result at the service layer and invalidate it whenever the underlying data changes, keeping the cache fresh without unnecessary DB hits.": "서비스 레이어에서 결과를 캐시하고 기반 데이터가 변경될 때마다 무효화하여 불필요한 DB 조회 없이 캐시를 최신 상태로 유지합니다.",
    "We should validate this in staging before pushing to production.": "프로덕션에 배포하기 전에 스테이징에서 검증해야 합니다.",
    "Here's a summary of what's included in this release.": "이번 릴리즈에 포함된 내용을 정리해 드립니다.",
    "We're seeing critical errors in production — I'm initiating a rollback.": "프로덕션에서 심각한 오류가 발생하고 있습니다. 롤백을 시작하겠습니다.",
    "We'll roll this out gradually using feature flags to monitor performance before a full release.": "전체 릴리즈 전에 성능을 모니터링하기 위해 피처 플래그를 사용하여 점진적으로 배포하겠습니다.",
    "Post-deploy metrics look stable — error rates and latency are within normal thresholds.": "배포 후 지표가 안정적입니다. 오류율과 지연 시간이 정상 범위 내에 있습니다.",
    "The deployment completed with zero downtime using a blue-green deployment strategy.": "블루-그린 배포 전략을 사용하여 무중단으로 배포가 완료됐습니다.",
    "I'd recommend a canary release — routing 5% of traffic to the new version before a full rollout.": "카나리아 릴리즈를 권장합니다. 전체 배포 전에 트래픽의 5%를 새 버전으로 라우팅하는 방식입니다.",
    "The deployment failed due to a misconfigured environment variable in the production config.": "프로덕션 설정에서 환경 변수가 잘못 구성되어 배포가 실패했습니다.",
    "We should define a clearer rollback plan before our next major release to reduce mean time to recovery.": "평균 복구 시간을 줄이기 위해 다음 주요 릴리즈 전에 더 명확한 롤백 계획을 수립해야 합니다.",
    "We need to fast-track this hotfix to production — it's directly impacting user sign-ups.": "이 핫픽스를 프로덕션에 빠르게 배포해야 합니다. 사용자 가입에 직접적인 영향을 미치고 있습니다.",
    "This code is legacy — it would benefit from a refactor.": "이 코드는 레거시입니다. 리팩토링하면 이점이 있을 것입니다.",
    "Making changes to this legacy code carries risk — we should add test coverage before touching it.": "이 레거시 코드를 변경하는 것은 위험 부담이 있습니다. 수정 전에 테스트 커버리지를 추가해야 합니다.",
    "Refactoring this module could yield a significant performance improvement and reduce code complexity.": "이 모듈을 리팩토링하면 성능이 크게 향상되고 코드 복잡성이 줄어들 수 있습니다.",
    "Before refactoring, I'd recommend adding tests to capture the current behavior.": "리팩토링 전에 현재 동작을 파악하는 테스트를 추가하는 것을 권장합니다.",
    "I'd recommend a strangler fig approach — gradually replacing legacy components while keeping the system functional.": "시스템을 정상적으로 유지하면서 레거시 컴포넌트를 점진적으로 교체하는 스트랭글러 피그 방식을 권장합니다.",
    "This legacy module has become a bottleneck — it's limiting our ability to scale and ship new features.": "이 레거시 모듈이 병목 지점이 됐습니다. 확장과 신규 기능 출시 능력을 제한하고 있습니다.",
    "Before we start, we should clearly define the scope of this refactor to avoid scope creep.": "시작하기 전에 범위 확장을 방지하기 위해 이번 리팩토링의 범위를 명확히 정의해야 합니다.",
    "Rather than refactoring everything at once, I'd suggest prioritizing by business impact and migration risk.": "한꺼번에 모든 것을 리팩토링하기보다는 비즈니스 영향도와 마이그레이션 리스크에 따라 우선순위를 정하는 것을 제안합니다.",
    "Data integrity validation is critical during migration — we should run parallel reads to verify consistency.": "마이그레이션 중 데이터 무결성 검증이 중요합니다. 일관성 확인을 위해 병렬 읽기를 실행해야 합니다.",
    "We should publish a deprecation timeline for this API to give clients time to migrate.": "클라이언트가 마이그레이션할 시간을 주기 위해 이 API의 사용 중단 일정을 공지해야 합니다.",
    "The README needs to be updated to reflect the recent changes.": "최근 변경 사항을 반영하기 위해 README를 업데이트해야 합니다.",
    "This function could use a brief comment explaining the expected input format.": "이 함수에 예상 입력 형식을 설명하는 간단한 주석을 추가하면 좋겠습니다.",
    "The API documentation is out of date — several endpoints added last sprint aren't documented yet.": "API 문서가 최신 상태가 아닙니다. 지난 스프린트에 추가된 엔드포인트 여러 개가 아직 문서화되지 않았습니다.",
    "I'd suggest documenting this as an ADR so future engineers understand the context behind this decision.": "향후 개발자들이 이 결정의 배경을 이해할 수 있도록 ADR로 문서화하는 것을 제안합니다.",
    "I'd like to improve our onboarding docs — it would help new engineers get up to speed faster.": "온보딩 문서를 개선하고 싶습니다. 새로운 개발자들이 더 빨리 적응하는 데 도움이 될 것입니다.",
    "Creating runbooks for common production issues would help reduce our mean time to resolution.": "일반적인 프로덕션 문제에 대한 런북을 만들면 평균 해결 시간을 줄이는 데 도움이 될 것입니다.",
    "These comments explain what the code does, but they should focus on why — the code itself already shows the what.": "이 주석들은 코드가 무엇을 하는지 설명하고 있지만, 이유에 집중해야 합니다. 코드 자체가 이미 무엇을 하는지 보여주고 있습니다.",
    "The documentation is quite verbose — I'd suggest adding a TL;DR section and a quick-start guide.": "문서가 다소 장황합니다. TL;DR 섹션과 빠른 시작 가이드를 추가하는 것을 제안합니다.",
    "Could you add more context to the PR description — specifically the motivation and the trade-offs considered?": "PR 설명에 더 많은 맥락을 추가해 주실 수 있나요? 특히 동기와 고려한 트레이드오프 부분이 필요합니다.",
    "The system architecture diagram is out of sync with the current implementation — we should update it before the next planning cycle.": "시스템 아키텍처 다이어그램이 현재 구현과 맞지 않습니다. 다음 계획 주기 전에 업데이트해야 합니다.",
    "Could you take a look at my PR? It's ready for review.": "제 PR을 검토해 주실 수 있나요? 리뷰 준비가 됐습니다.",
    "I'm a bit stuck on this — would anyone be available to pair on it?": "이 부분에서 막혀 있는데, 페어 프로그래밍을 같이 해주실 분 계신가요?",
    "Our PR review cycle is a bit slow — would it help to set a 24-hour review SLA?": "PR 리뷰 사이클이 다소 느린데, 24시간 리뷰 SLA를 설정하면 도움이 될까요?",
    "I'd like to propose a regular knowledge-sharing session to help level up the team's understanding of our system.": "팀의 시스템 이해도 향상을 위해 정기적인 지식 공유 세션을 제안하고 싶습니다.",
    "I think this would be better handled by someone with more context on the auth service.": "인증 서비스에 대해 더 많은 이해가 있는 사람이 처리하는 것이 더 좋을 것 같습니다.",
    "Our on-call rotation is leading to burnout — I'd suggest reducing the rotation to two-week cycles and adding better alerting.": "온콜 로테이션이 번아웃을 유발하고 있습니다. 로테이션을 2주 주기로 줄이고 더 나은 알림을 추가하는 것을 제안합니다.",
    "Our cross-team dependencies are creating bottlenecks in our release pipeline — we should discuss better decoupling.": "팀 간 의존성이 릴리즈 파이프라인에 병목을 만들고 있습니다. 더 나은 분리 방안에 대해 논의해야 합니다.",
    "I'd like to share the key learnings from this incident so we can prevent similar issues in the future.": "향후 유사한 문제를 방지하기 위해 이번 장애에서 얻은 주요 교훈을 공유하고 싶습니다.",
    "I'd suggest formalizing our coding conventions in a shared style guide and enforcing them via linter rules.": "코딩 컨벤션을 공유 스타일 가이드에 공식화하고 린터 규칙으로 적용하는 것을 제안합니다.",
    "I think senior engineers should be more involved in shaping the technical roadmap early in the planning cycle.": "시니어 엔지니어들이 계획 주기 초반에 기술 로드맵 수립에 더 많이 참여해야 할 것 같습니다.",

    # ── Product Manager ───────────────────────────────────────────────────────
    "We're planning to release the new feature next quarter.": "다음 분기에 새 기능을 출시할 계획입니다.",
    "This feature takes priority over that one.": "이 기능이 저것보다 우선입니다.",
    "Our goal for this sprint is to finish the login flow.": "이번 스프린트 목표는 로그인 플로우를 완성하는 것입니다.",
    "Let's estimate the effort for each ticket.": "각 티켓의 작업량을 추정해 봅시다.",
    "The user needs to be able to reset their password.": "사용자가 비밀번호를 재설정할 수 있어야 합니다.",
    "The requirements have changed since yesterday.": "요구사항이 어제 이후로 변경됐습니다.",
    "I want to give you an update on our progress.": "진행 상황을 공유드리고 싶습니다.",
    "I'll send the agenda ahead of tomorrow's meeting.": "내일 회의 전에 안건을 보내드리겠습니다.",
    "We should decide which feature to develop first.": "어떤 기능을 먼저 개발할지 결정해야 합니다.",
    "Let's pick the most important item from the backlog.": "백로그에서 가장 중요한 항목을 선택합시다.",
    "Our key metrics for this month look good.": "이번 달 주요 지표가 좋아 보입니다.",
    "DAU increased by 15% compared to last week.": "DAU가 지난주 대비 15% 증가했습니다.",
    "I think we did a great job this sprint.": "이번 스프린트 정말 잘한 것 같습니다.",
    "We should improve our communication next sprint.": "다음 스프린트에서는 소통을 개선해야 합니다.",
    "Let me show you the new feature we built.": "우리가 만든 새 기능을 보여드리겠습니다.",
    "The beta test results were very positive.": "베타 테스트 결과가 매우 긍정적이었습니다.",
    "Can we schedule an interview with some users?": "사용자 몇 명과 인터뷰 일정을 잡을 수 있을까요?",
    "Users are feeling confused about the onboarding flow.": "사용자들이 온보딩 플로우에 대해 혼란스러워하고 있습니다.",
    "We're planning to launch the feature this Friday.": "이번 주 금요일에 기능을 출시할 계획입니다.",
    "We will monitor the launch for any issues.": "출시 후 문제가 없는지 모니터링할 것입니다.",
    "Our main focus for Q3 is improving user retention.": "3분기의 주요 목표는 사용자 리텐션 개선입니다.",
    "This change will help us achieve our business goals.": "이 변경 사항은 비즈니스 목표 달성에 도움이 될 것입니다.",
    "We included this because it has a high impact on our users.": "사용자에게 큰 영향을 미치기 때문에 이것을 포함했습니다.",
    "I think we're overcommitting this sprint.": "이번 스프린트에 너무 많은 것을 약속하는 것 같습니다.",
    "Our sprint goal needs to be measurable.": "스프린트 목표는 측정 가능해야 합니다.",
    "We should carve out time for tech debt tickets this sprint.": "이번 스프린트에 기술 부채 티켓을 처리할 시간을 확보해야 합니다.",
    "The requirements aren't clear enough to move forward with development.": "요구사항이 개발을 진행하기에 충분히 명확하지 않습니다.",
    "We didn't account for the edge cases in the spec.": "스펙에서 엣지 케이스를 고려하지 않았습니다.",
    "This feature falls outside the scope of this sprint.": "이 기능은 이번 스프린트 범위를 벗어납니다.",
    "We're behind schedule due to an unexpected technical issue.": "예상치 못한 기술적 문제로 일정이 지연되고 있습니다.",
    "We'll revisit your request next quarter.": "요청 사항은 다음 분기에 다시 검토하겠습니다.",
    "We need additional resources to deliver this on time.": "제때 납품하려면 추가 리소스가 필요합니다.",
    "Let's prioritize based on impact versus effort.": "영향도 대비 노력을 기준으로 우선순위를 정합시다.",
    "This feature doesn't deliver core user value, so I'd recommend pushing it back.": "이 기능은 핵심 사용자 가치를 제공하지 않으므로 뒤로 미루는 것을 권장합니다.",
    "The bug fix is more urgent than shipping new features.": "버그 수정이 새 기능 출시보다 더 긴급합니다.",
    "Our conversion rate is falling short of our target.": "전환율이 목표에 미치지 못하고 있습니다.",
    "We need to investigate why our metrics have dropped.": "지표가 하락한 이유를 조사해야 합니다.",
    "The A/B test results are statistically significant.": "A/B 테스트 결과가 통계적으로 유의미합니다.",
    "The team showed great collaboration this sprint.": "이번 스프린트에서 팀이 훌륭한 협업을 보여줬습니다.",
    "We ran into communication issues again this sprint.": "이번 스프린트에서도 소통 문제가 있었습니다.",
    "Let's define action items to improve our team process.": "팀 프로세스 개선을 위한 액션 아이템을 정의합시다.",
    "This feature closely aligns with what users are trying to accomplish.": "이 기능은 사용자가 이루려는 목표와 잘 맞습니다.",
    "There are some UX issues we need to address.": "해결해야 할 UX 문제가 몇 가지 있습니다.",
    "This feature performed better than expected.": "이 기능이 예상보다 더 좋은 성과를 냈습니다.",
    "Our user interviews surfaced some key insights.": "사용자 인터뷰를 통해 중요한 인사이트가 드러났습니다.",
    "The user feedback validated our assumptions.": "사용자 피드백이 우리의 가정을 검증해 줬습니다.",
    "We're seeing a recurring pattern of user complaints.": "사용자 불만이 반복적인 패턴으로 나타나고 있습니다.",
    "If we see any issues, we'll roll back the feature immediately.": "문제가 발생하면 즉시 기능을 롤백하겠습니다.",
    "We're planning a phased rollout using feature flags.": "피처 플래그를 사용한 단계적 배포를 계획하고 있습니다.",
    "We'll keep a close eye on key metrics in the first 48 hours post-launch.": "출시 후 48시간 동안 주요 지표를 면밀히 모니터링하겠습니다.",
    "Competitors are gaining ground in this space.": "경쟁사들이 이 분야에서 영향력을 키우고 있습니다.",
    "Let's align on which features should be included in the MVP.": "MVP에 포함될 기능들에 대해 합의합시다.",
    "This feature directly addresses a core user pain point.": "이 기능은 핵심 사용자 불편함을 직접적으로 해결합니다.",
    "Is everyone aligned on our product vision?": "모두가 제품 비전에 대해 동의하고 있나요?",
    "The biggest technical risk this sprint is the database migration.": "이번 스프린트의 가장 큰 기술적 리스크는 데이터베이스 마이그레이션입니다.",
    "Our churn rate is climbing, and we need to act quickly.": "이탈률이 오르고 있어 빠르게 행동해야 합니다.",
    "We're aiming to reduce technical debt in the next release.": "다음 릴리즈에서 기술 부채를 줄이는 것을 목표로 하고 있습니다.",
    "Without user research, it's hard to validate our assumptions.": "사용자 리서치 없이는 우리의 가정을 검증하기 어렵습니다.",
    "We hit most of our OKR targets this quarter.": "이번 분기에 대부분의 OKR 목표를 달성했습니다.",
    "Customer satisfaction has improved since the new feature launch.": "새 기능 출시 이후 고객 만족도가 향상됐습니다.",
    "We identified performance issues during internal testing.": "내부 테스트 중 성능 문제를 발견했습니다.",
    "We're planning a mobile app redesign for next quarter.": "다음 분기 모바일 앱 리디자인을 계획하고 있습니다.",
    "This feature request isn't aligned with our current strategy.": "이 기능 요청은 현재 전략과 맞지 않습니다.",
    "Our long-term vision is grounded in short-term bets that deliver user value.": "우리의 장기 비전은 사용자 가치를 제공하는 단기 시도들을 기반으로 합니다.",
    "Our velocity deviated from our estimates this sprint.": "이번 스프린트에서 속도가 예상치와 달랐습니다.",
    "Ambiguous requirements will introduce risk late in the development cycle.": "모호한 요구사항은 개발 후반부에 리스크를 초래할 것입니다.",
    "Failure to align stakeholder expectations early can lead to friction down the road.": "초기에 이해관계자 기대치를 조율하지 않으면 나중에 마찰이 생길 수 있습니다.",
    "We'll evaluate the backlog across three dimensions: user impact, strategic fit, and feasibility.": "백로그를 사용자 영향도, 전략적 적합성, 실현 가능성의 세 가지 기준으로 평가하겠습니다.",
    "Cohort analysis reveals that day-7 retention is significantly lower among new users.": "코호트 분석 결과 신규 사용자의 7일 리텐션이 현저히 낮은 것으로 나타났습니다.",
    "This sprint's shortfall points to a process gap, not a people issue.": "이번 스프린트의 부진은 사람의 문제가 아니라 프로세스 문제를 가리킵니다.",
    "Our product is losing its competitive differentiation.": "우리 제품이 경쟁적 차별성을 잃어가고 있습니다.",
    "The user interviews fundamentally challenged our core assumptions.": "사용자 인터뷰가 우리의 핵심 가정에 근본적으로 의문을 제기했습니다.",
    "Before launch, let's review the risk matrix and identify any potential blockers.": "출시 전에 리스크 매트릭스를 검토하고 잠재적인 방해 요소를 파악합시다.",
    "Improvements in our product metrics tend to correlate with stronger business outcomes.": "제품 지표 개선은 더 강한 비즈니스 성과와 상관관계를 보이는 경향이 있습니다.",
    "Unresolved cross-team dependencies are a critical risk to our launch timeline.": "해결되지 않은 팀 간 의존성은 출시 일정에 치명적인 리스크입니다.",
    "This feature is designed to support our existing monetization strategy.": "이 기능은 기존 수익화 전략을 지원하도록 설계됐습니다.",
    "We'd benefit from deeper user research before committing to a build direction.": "개발 방향을 확정하기 전에 더 심층적인 사용자 리서치를 하면 도움이 될 것입니다.",
    "Shifting market dynamics call for a reassessment of our current strategy.": "변화하는 시장 역학이 현재 전략의 재평가를 요구하고 있습니다.",
    "Our current product direction seems to be optimized for internal convenience rather than user needs.": "현재 제품 방향이 사용자 니즈보다 내부 편의에 최적화된 것 같습니다.",
    "We need to embed a data-driven decision-making culture across the team.": "팀 전체에 데이터 기반 의사결정 문화를 정착시켜야 합니다.",
    "Post-launch, we'll analyze performance variances across user segments.": "출시 후 사용자 세그먼트별 성과 차이를 분석하겠습니다.",
    "The partner integration introduces external dependencies that could affect our roadmap timeline.": "파트너 통합은 로드맵 일정에 영향을 줄 수 있는 외부 의존성을 만듭니다.",
    "At this stage, retention is a higher-leverage strategy than acquisition.": "이 단계에서는 리텐션이 신규 유입보다 더 높은 레버리지를 가진 전략입니다.",
    "Please prioritize the most critical task first.": "가장 중요한 작업을 먼저 처리해 주세요.",
    "We need to define success metrics before we start.": "시작하기 전에 성공 지표를 정의해야 합니다.",
    "The new feature will be delivered later than expected.": "새 기능이 예상보다 늦게 출시될 것입니다.",
    "We should shorten our feedback loop with users.": "사용자와의 피드백 루프를 단축해야 합니다.",
    "For this release, performance optimization takes precedence over UX improvements.": "이번 릴리즈에서는 UX 개선보다 성능 최적화가 우선입니다.",
    "I want to make sure everyone is aligned on our product goals.": "모두가 제품 목표에 대해 동의하고 있는지 확인하고 싶습니다.",
    "We should incorporate the customer support issues into the next sprint.": "고객 지원 문제를 다음 스프린트에 반영해야 합니다.",
    "Our roadmap needs to be calibrated against our actual engineering capacity.": "로드맵을 실제 엔지니어링 역량에 맞게 조정해야 합니다.",
    "Our product strategy should optimize for long-term user value over short-term revenue gains.": "제품 전략은 단기 수익보다 장기적인 사용자 가치에 최적화되어야 합니다.",
    "Before scaling the platform, we need to ensure core feature stability.": "플랫폼을 확장하기 전에 핵심 기능의 안정성을 확보해야 합니다.",
    "We should compare LTV across acquisition channels to optimize our marketing spend.": "마케팅 지출을 최적화하기 위해 유입 채널별 LTV를 비교해야 합니다.",
    "We should conduct thorough market research before committing to a strategic direction.": "전략적 방향을 확정하기 전에 철저한 시장 조사를 실시해야 합니다.",
    "Different user segments require tailored onboarding experiences.": "서로 다른 사용자 세그먼트는 맞춤화된 온보딩 경험을 필요로 합니다.",
    "This feature delivers disproportionate value to our core user segment.": "이 기능은 핵심 사용자 세그먼트에 불균형적으로 높은 가치를 제공합니다.",
    "We need to build a culture of rapid, small-scale experimentation.": "빠르고 소규모의 실험 문화를 구축해야 합니다.",
    "Our current metrics capture surface-level growth but don't reflect true user value.": "현재 지표는 표면적인 성장을 나타내지만 실제 사용자 가치를 반영하지 않습니다.",
    "Investing heavily in growth before achieving product-market fit is premature.": "제품-시장 적합성을 달성하기 전에 성장에 많은 투자를 하는 것은 시기상조입니다.",
}

wb = openpyxl.load_workbook("/Users/design_euini/Downloads/3min_biz_english_all_v2 (1).xlsx")
job_map = {
    "마케터": "marketer",
    "프로덕트 디자이너": "designer",
    "개발자": "developer",
    "PM": "pm",
}
out = "/Users/design_euini/Downloads/lessons_seed.csv"

missing = []

with open(out, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["job", "difficulty", "situation", "correct", "correct_ko", "wrong1", "wrong2", "reason", "is_premium"])
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows(min_row=2, values_only=True):
            if not row[3]:
                continue
            num, difficulty, job_ko, situation, correct, wrong1, wrong2, reason, *_ = row
            job = job_map.get(job_ko, job_ko)
            correct_ko = correct_ko_map.get(correct, "")
            if not correct_ko:
                missing.append(correct)
            writer.writerow([job, difficulty, situation, correct, correct_ko, wrong1, wrong2 or "", reason, "false"])

if missing:
    print(f"[경고] correct_ko 없는 항목 {len(missing)}개:")
    for m in missing:
        print(f"  {m!r}")
else:
    print("모든 correct_ko 매핑 완료!")

print(f"생성 완료: {out}")
